# Alacritty Configuration - Catppuccin Mocha Theme
# With dynamic font sizing and window decorations

[general]
import = []
live_config_reload = true

[env]
TERM = "alacritty"

[window]
# Window decorations and borders
decorations = "full"  # Shows title bar with minimize/maximize/close buttons
opacity = 0.95
blur = false
startup_mode = "Windowed"
dynamic_title = true
decorations_theme_variant = "Dark"

# Window dimensions and positioning
dimensions = { columns = 80, lines = 24 }
position = "None"  # Let window manager decide
dynamic_padding = false
resize_increments = false

# Window padding and borders
padding = { x = 10, y = 10 }
option_as_alt = "OnlyLeft"

[scrolling]
history = 2000
multiplier = 3

[font]

# Dynamic font size - can be adjusted with keyboard shortcuts
size = 12.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#F9E2AF"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Off" }
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15

[terminal]
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Right", action = "PasteSelection" },
]

# Colors - Catppuccin Mocha
[colors]
transparent_background_colors = false

[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#BAC2DE"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search]
matches = { foreground = "#1E1E2E", background = "#A6ADC8" }
focused_match = { foreground = "#1E1E2E", background = "#A6E3A1" }

[colors.footer_bar]
foreground = "#CDD6F4"
background = "#181825"

[colors.hints]
start = { foreground = "#1E1E2E", background = "#F9E2AF" }
end = { foreground = "#1E1E2E", background = "#A6ADC8" }

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

# Essential keyboard shortcuts only
# Font size control
[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

# Copy and paste
[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false
